routes/web.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::post('users/{user}/restore', [UserController::class, 'restore'])->name('users.restore');
    Route::delete('users/{user}/delete', [UserController::class, 'delete'])->name('users.delete');
});



require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'avatar',
        'type',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getAvatarAttribute($avatar)
    {
        if(!isset($avatar)){
            return asset('storage/avatar.jpg');
        }

        return asset('storage/' . $avatar);
    }

    public function getNameAttribute($value)
    {

        return ucwords($value);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (empty(request()->type)){
            $users = User::paginate(5);
            return view('dashboard.index', [
                'users' => $users
            ]);
        }else{
            $users = User::where('type', request()->type)->paginate(5);
            return view('dashboard.index', [
                'users' => $users
            ]);
        }
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\UserUpdateRequest;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (empty(request()->type)) {

            $users = User::onlyTrashed()->paginate(5);
            return view('dashboard.users.index', [
                'users' => $users
            ]);
        } else {
            $users = User::onlyTrashed()->where('type', request()->type)->paginate(5);
            return view('dashboard.users.index', [
                'users' => $users
            ]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('dashboard.users.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('dashboard.users.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $data = User::findOrFail($user->id);

        if (empty($request->password)) {
            $request->merge([
                'password' => $data->password
            ]);
        }


        $data->update($request->all());




        return  back()->with('message', 'User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($user)
    {

        User::findOrFail($user)->delete();

        return back()->with('message', 'User deleted successfully');
    }

    public function restore($user)
    {
        User::withTrashed()->findOrFail($user)->restore();
        return back()->with('message', 'User restored successfully');;
    }

    public function delete($user)
    {
        User::withTrashed()->findOrFail($user)->forceDelete();
        return back()->with('message', 'User deleted permanently successfully');;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if(session()->has('message'))
            <div class="my-4 alert alert-success">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span> {{ session()->get('message') }}</span>
                </div>
            </div>
            @endif
            <div class="my-4 flex justify-end btn-group">
                <a href="{{ route('dashboard') }}" class="btn btn-xs {{ empty(request()->type) ? 'btn-active' : 'btn-ghost' }}">All</a>
                <a href="{{ route('dashboard', ['type' => 1]) }}" class="btn btn-xs {{ request()->type == 1 ? 'btn-active' : 'btn-ghost' }}">Admins</a>
                <a href="{{ route('dashboard', ['type' => 2]) }}" class="btn btn-xs {{ request()->type == 2 ? 'btn-active' : 'btn-ghost' }}">Users</a>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="overflow-x-auto w-full">
                    <table class="table w-full">
                        <!-- head -->
                        <thead>
                            <tr>
                                <th>Avatar</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- row 1 -->
                            @if(!empty($users))
                                @foreach($users as $user)
                                <tr>
                                    <td>
                                        <div class="flex items-center space-x-3">
                                            <div class="avatar">
                                                <div class="w-12 h-12 mask mask-squircle">
                                                    <img src="{{ $user->avatar}}" alt="Avatar Tailwind CSS Component">
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        {{ $user->name}}

                                    </td>
                                    <td>{{ $user->type == 1 ? 'Admin' : 'User'}}</td>
                                    <th>
                                        <!-- The button to open modal -->
                                        <a href="#details-modal-{{ $user->id}}" class="btn btn-ghost btn-xs">details</a>
                                        <a href="#update-modal-{{ $user->id}}" class="btn btn-success btn-xs">update</a>
                                        <a href="#delete-modal-{{ $user->id}}" class="btn btn-error btn-xs">delete</a>
                                    </th>
                                </tr>

                                <!-- Put this part before </body> tag -->
                                <div class="modal" id="details-modal-{{ $user->id}}">
                                    <div class="modal-box items-center text-center">

                                        <div class="avatar">
                                            <div class="w-24 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
                                                <img src="{{ $user->avatar }}">
                                            </div>
                                        </div>
                                        <h3 class="font-bold text-lg">{{ $user->name }}</h3>
                                        <p class="py-2">{{ $user->email }}</p>
                                        <div class="badge badge-ghost">{{ $user->type == 1 ? 'admin' : 'user' }}</div>
                                        <div class="flex justify-center modal-action">
                                            <a href="#" class="btn btn-error btn-xs">close!</a>
                                        </div>
                                    </div>
                                </div>

                                <!-- Put this part before </body> tag -->
                                <div class="modal flex flex-col justify-center space-x-3" id="update-modal-{{ $user->id}}">
                                    <div class="modal-box">
                                        <form action="{{ route('users.update', $user) }}" method="POST" id="updateForm-{{ $user->id}}" enctype="multipart/form-data">
                                            @method('PUT')
                                            @csrf
                                            <div class="form-control">
                                                <label class="label">
                                                    <span class="label-text">Name</span>
                                                </label>
                                                <input type="text" name="name" placeholder="{{ $user->name }}" value="{{ $user->name }}" class="input input-bordered w-full max-w-xs">
                                            </div>

                                            <div class="form-control">
                                                <label class="label">
                                                    <span class="label-text">Email</span>
                                                </label>
                                                <input type="text" name="email" placeholder="{{ $user->email }}" value="{{ $user->email }}" class="input input-bordered w-full max-w-xs">
                                            </div>

                                            <div class="form-control">
                                                <label class="label">
                                                    <span class="label-text">Password</span>
                                                </label>
                                                <input type="password" name="password" placeholder="Password" class="input input-bordered w-full max-w-xs">
                                            </div>


                                            <div class="form-control">
                                                <label class="label">
                                                    <span class="label-text">Type</span>
                                                </label>
                                                <select name="type" class="select w-full max-w-xs select-warning">
                                                    <option value="{{ $user->type == 1 ? 1 : 2 }}" selected>{{ $user->type == 1 ? 'Admin' : 'User' }}</option>
                                                    <option value="{{ $user->type == 2 ? 1 : 2 }}">{{ $user->type == 1 ? 'User' : 'Admin' }}</option>
                                                </select>
                                            </div>
                                            <div class="form-control">
                                                <label class="label">
                                                    <span class="label-text">Choose an avatar</span>
                                                </label>
                                                <input type="file" name="avatar" class="block w-full text-sm text-slate-500
        file:mr-4 file:py-2 file:px-4
        file:rounded-full file:border-0
        file:text-sm file:font-semibold
        file:bg-violet-50 file:text-violet-700
        hover:file:bg-violet-100
        " />
                                            </div>
                                        </form>

                                        <div class="flex justify-center modal-action">
                                            <button type="submit" form="updateForm-{{ $user->id}}" class="btn btn-success btn-xs">update!</button>
                                            <a href="#" class="btn btn-error btn-xs">close!</a>
                                        </div>
                                    </div>
                                </div>

                                <!-- Put this part before </body> tag -->
                                <div class="modal" id="delete-modal-{{ $user->id}}">
                                    <div class="modal-box items-center text-center">
                                        <h2 class="font-bold text-lg">Delete!</h2>
                                        <p>Are your sure you want to delete this user.</p>
                                        <div class="flex justify-center modal-action">
                                            <form action="{{ route('users.destroy', $user) }}" method="post">
                                                @method("DELETE")
                                                @csrf
                                                <button type="submit" class="btn btn-error btn-xs">delete</button>
                                            </form>

                                            <a href="#" class="btn btn-success btn-xs">close!</a>
                                        </div>

                                    </div>

                                </div>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-4 lg:px-4">
            @if(!empty($users))
                {{ $users->withQueryString()->links()}}
            @endif
        </div>
    </div>

</x-app-layout>

resources/views/dashboard/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Deleted users') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if(session()->has('message'))
                <div class="my-4 alert alert-success">
                    <div>
                        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        <span> {{ session()->get('message') }}</span>
                    </div>
                </div>
            @endif
            <div class="my-4 flex justify-end btn-group">
                <a href="{{ route('users.index') }}" class="btn btn-xs {{ empty(request()->type) ? 'btn-active' : 'btn-ghost' }}">All</a>
                <a href="{{ route('users.index', ['type' => 1]) }}" class="btn btn-xs {{ request()->type == 1 ? 'btn-active' : 'btn-ghost' }}">Admins</a>
                <a href="{{ route('users.index', ['type' => 2]) }}" class="btn btn-xs {{ request()->type == 2 ? 'btn-active' : 'btn-ghost' }}">Users</a>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="overflow-x-auto w-full">
                    <table class="table w-full">
                        <!-- head -->
                        <thead>
                            <tr>
                                <th>Avatar</th>
                                <th>Name</th>
                                <th>Type</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- row 1 -->
                            @if(!empty($users))
                                @foreach($users as $user)
                                <tr>
                                    <td>
                                        <div class="flex items-center space-x-3">
                                            <div class="avatar">
                                                <div class="w-12 h-12 mask mask-squircle">
                                                    <img src="{{ $user->avatar}}" alt="Avatar Tailwind CSS Component">
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        {{ $user->name}}

                                    </td>
                                    <td>{{ $user->type == 1 ? 'Admin' : 'User'}}</td>
                                    <th>
                                        <!-- The button to open modal -->
                                        <form action="{{ route('users.restore', $user) }}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn btn-success btn-xs">restore</button>
                                        </form>
                                        <form action="{{ route('users.delete', $user) }}" method="POST">
                                            @method("DELETE")
                                            @csrf
                                            <button type="submit" class="btn btn-error btn-xs">delete permanently</button>
                                        </form>
                                    </th>
                                </tr>
                                @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-4 lg:px-4">
        @if(!empty($users))
            {{ $users->links()}}
        @endif
        </div>
    </div>

</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <x-dropdown-link :href="route('users.index')">
                            Deleted users
                        </x-dropdown-link>
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>